# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0048_auto_20160110_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='administrator_code_generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_code_competition_set', to='code_based_auth.CodeGenerator', verbose_name=b''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competitor_code_generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_code_competition_set', to='code_based_auth.CodeGenerator', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='duration',
            field=models.IntegerField(default=3600, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.DateTimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='motd',
            field=models.TextField(blank=True, verbose_name='motd'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='promoted'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='questionsets',
            field=models.ManyToManyField(through='bober_simple_competition.CompetitionQuestionSet', to='bober_simple_competition.QuestionSet', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='title'),
        ),
    ]
