# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0049_auto_20160905_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='administrator_code_generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_code_competition_set', to='code_based_auth.CodeGenerator', verbose_name='administrator code generator'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competitor_code_generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_code_competition_set', to='code_based_auth.CodeGenerator', verbose_name='competitor code generator'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='motd',
            field=models.TextField(blank=True, verbose_name='message of the day'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='questionsets',
            field=models.ManyToManyField(through='bober_simple_competition.CompetitionQuestionSet', to='bober_simple_competition.QuestionSet', verbose_name='Question sets'),
        ),
    ]
