# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0051_auto_20160919_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[(b'sl', 'Slovenian'), (b'sr_', 'Serbian'), (b'en', 'English'), (b'tr', 'Turkish')], max_length=7),
        ),
    ]
