# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0056_auto_20171104_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('female', 'Female'), ('na', 'Not applicable')], max_length=16),
        ),
        migrations.AlterField(
            model_name='codeeffect',
            name='effect',
            field=models.CharField(choices=[('let_manage', 'Allow the creator to manage the profile of anyone using this code'), ('let_manage_recursive', 'Allow the creator and their managers to manage the profile of anyone using this code')], max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='question',
            name='authors',
            field=models.TextField(default='Various'),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('en', 'English')], max_length=7),
        ),
        migrations.AlterField(
            model_name='question',
            name='license',
            field=models.TextField(default='Creative commons CC-By'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='question',
            name='verification_function',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='verification_function_type',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'javascript_gostisa'), (2, 'javascript_france'), (16, 'python')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='version',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(null=True, upload_to='resources'),
        ),
        migrations.AlterField(
            model_name='resourcecache',
            name='file',
            field=models.FileField(upload_to='caches'),
        ),
        migrations.AlterField(
            model_name='resourcecache',
            name='format',
            field=models.CharField(choices=[('zip', 'ZIP'), ('raw', 'raw data')], max_length=16),
        ),
    ]
