# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0057_auto_20180320_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='public',
            field=models.BooleanField(default=True, help_text='Public competitions are listed on the competiton list page', verbose_name='public competition'),
        )
    ]
