# Generated by Django 3.2.9 on 2021-11-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0060_auto_20181013_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('sl', 'Slovenian'), ('en', 'English')], max_length=7),
        ),
    ]
