# Generated by Django 4.2.6 on 2023-11-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0061_auto_20211101_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('sl', 'Slovenian')], max_length=7),
        ),
    ]
