# Generated by Django 6.0.3 on 2026-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bober_simple_competition", "0062_alter_competitor_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="language",
            field=models.CharField(choices=[("en", "English")], max_length=7),
        ),
    ]
