# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_tasks', '0007_auto_20160905_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='label',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='resources',
            name='language',
            field=models.CharField(choices=[('en', 'English')], max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='interaction_type',
            field=models.CharField(default='non-interactive', max_length=45),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='language_locale',
            field=models.CharField(blank=True, choices=[('en', 'English')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='template',
            field=models.CharField(choices=[('default', 'default.html'), ('vertical_answers', 'vertical_answers.html')], max_length=255),
        ),
    ]
