# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_tasks', '0008_auto_20160919_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='language',
            field=models.CharField(choices=[(b'sl', 'Slovenian'), (b'sr_', 'Serbian'), (b'en', 'English'), (b'tr', 'Turkish')], max_length=8),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='it_is_informatics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='language_locale',
            field=models.CharField(blank=True, choices=[(b'sl', 'Slovenian'), (b'sr_', 'Serbian'), (b'en', 'English'), (b'tr', 'Turkish')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='solution',
            field=models.TextField(),
        ),
    ]
