# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-12 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bober_tasks', '0009_auto_20161101_1715'),
        ('bober_tasks', '0008_auto_20180320_0814'),
    ]

    operations = [
    ]
