# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_tasks', '0010_merge_20181012_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='language',
            field=models.CharField(choices=[('sl', 'Slovenian'), ('sr_', 'Serbian'), ('en', 'English'), ('tr', 'Turkish')], max_length=8),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='language_locale',
            field=models.CharField(blank=True, choices=[('sl', 'Slovenian'), ('sr_', 'Serbian'), ('en', 'English'), ('tr', 'Turkish')], max_length=8, null=True),
        ),
    ]
