# Generated by Django 3.2.9 on 2021-11-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_tasks', '0011_auto_20181013_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='language',
            field=models.CharField(choices=[('sl', 'Slovenian'), ('en', 'English')], max_length=8),
        ),
        migrations.AlterField(
            model_name='tasktranslation',
            name='language_locale',
            field=models.CharField(blank=True, choices=[('sl', 'Slovenian'), ('en', 'English')], max_length=8, null=True),
        ),
    ]
