# Generated by Django 6.0.3 on 2026-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bober_tasks", "0012_auto_20211101_2231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="language",
            field=models.CharField(choices=[("en", "English")], max_length=8),
        ),
        migrations.AlterField(
            model_name="tasktranslation",
            name="language_locale",
            field=models.CharField(
                blank=True, choices=[("en", "English")], max_length=8, null=True
            ),
        ),
    ]
