# Generated by Django 4.2.6 on 2023-11-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_paper_submissions', '0002_auto_20180320_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniordefaultyear',
            name='school_category',
            field=models.CharField(choices=[('ELEMENTARY', 'Osnovna šola'), ('HIGHSCHOOL', 'Srednja šola'), ('KINDERGARDEN', 'Vrtec')], max_length=24),
        ),
    ]
