# Generated by Django 6.0.3 on 2026-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bober_paper_submissions", "0003_alter_juniordefaultyear_school_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="juniordefaultyear",
            name="school_category",
            field=models.CharField(
                choices=[
                    ("ELEMENTARY", "Elementary school"),
                    ("HIGHSCHOOL", "High school"),
                    ("KINDERGARDEN", "Kindergarden"),
                ],
                max_length=24,
            ),
        ),
    ]
