BBBB BBBB BBBBBBXXXXXXXXX XXXXX
XXXXXX
  XXXXXXXXXXXXX gettext(u'Popup closing...') XXXXXXXXXXXXXXX
  XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX
            XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXXX
XXXXXXX
