BBBB BBBB BBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    BBBBB BBBBB
        BB BBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX FFFFX
            XXXXXXX gettext(u'Change selected %(model)s') SSSSSS SSSSSSSS SSSSSSSSSXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Change') XXX
        XXXX
        BBBBB
        BB BBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXX FFFFX
            XXXXXXX gettext(u'Add another %(model)s') SSS SSSSSSS SSSSSSSSSXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Add') XXX
        XXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX FFFFX
            XXXXXXX gettext(u'Delete selected %(model)s') SSSSSS SSSSSSSS SSSSSSSSSXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Delete') XXX
        XXXX
        BBBBB
    BBBBBBBB
XXXXXX
