# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 15:17
from __future__ import unicode_literals

import code_based_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_based_auth', '0010_auto_20151025_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='value',
            field=code_based_auth.models.CodeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='codegenerator',
            name='codes',
            field=models.ManyToManyField(blank=True, to='code_based_auth.Code'),
        ),
    ]
