# Generated by Django 3.2.9 on 2021-11-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_based_auth', '0014_auto_20181013_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecomponent',
            name='hash_algorithm',
            field=models.CharField(blank=True, choices=[('sha512_256', 'sha512_256'), ('whirlpool', 'whirlpool'), ('sha512', 'sha512'), ('shake_256', 'shake_256'), ('shake_128', 'shake_128'), ('sha3_224', 'sha3_224'), ('sha256', 'sha256'), ('md5', 'md5'), ('sha3_256', 'sha3_256'), ('md5-sha1', 'md5-sha1'), ('blake2s', 'blake2s'), ('sha224', 'sha224'), ('ripemd160', 'ripemd160'), ('sha1', 'sha1'), ('sha384', 'sha384'), ('blake2b', 'blake2b'), ('sm3', 'sm3'), ('sha3_384', 'sha3_384'), ('sha3_512', 'sha3_512'), ('sha512_224', 'sha512_224'), ('md4', 'md4'), ('noop', 'No hash')], max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='CodeRevocation',
        ),
    ]
