# Generated by Django 3.2.9 on 2021-11-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_based_auth', '0015_auto_20211101_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeformat',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='codecomponent',
            name='hash_algorithm',
            field=models.CharField(blank=True, choices=[('sha1', 'sha1'), ('sha384', 'sha384'), ('sha512', 'sha512'), ('md5', 'md5'), ('sha3_384', 'sha3_384'), ('md5-sha1', 'md5-sha1'), ('sm3', 'sm3'), ('whirlpool', 'whirlpool'), ('md4', 'md4'), ('blake2s', 'blake2s'), ('shake_128', 'shake_128'), ('sha256', 'sha256'), ('sha3_224', 'sha3_224'), ('sha512_224', 'sha512_224'), ('sha3_256', 'sha3_256'), ('sha512_256', 'sha512_256'), ('blake2b', 'blake2b'), ('shake_256', 'shake_256'), ('sha3_512', 'sha3_512'), ('ripemd160', 'ripemd160'), ('sha224', 'sha224'), ('noop', 'No hash')], max_length=16, null=True),
        ),
    ]
