# Generated by Django 3.2.9 on 2021-11-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_based_auth', '0016_auto_20211104_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecomponent',
            name='hash_algorithm',
            field=models.CharField(blank=True, choices=[('blake2b', 'blake2b'), ('blake2s', 'blake2s'), ('md4', 'md4'), ('md5', 'md5'), ('md5-sha1', 'md5-sha1'), ('ripemd160', 'ripemd160'), ('sha1', 'sha1'), ('sha224', 'sha224'), ('sha256', 'sha256'), ('sha384', 'sha384'), ('sha3_224', 'sha3_224'), ('sha3_256', 'sha3_256'), ('sha3_384', 'sha3_384'), ('sha3_512', 'sha3_512'), ('sha512', 'sha512'), ('sha512_224', 'sha512_224'), ('sha512_256', 'sha512_256'), ('shake_128', 'shake_128'), ('shake_256', 'shake_256'), ('sm3', 'sm3'), ('whirlpool', 'whirlpool'), ('noop', 'No hash')], max_length=16, null=True),
        ),
    ]
