<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Home' => 'Domov',
  'The button type "{type}" is not supported.' => 'The button type "{type}" is not supported.',
  'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
  'Delete' => 'Izbriši',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Prikaz {start}-{end} od 1 zapisa.|Prikaz {start}-{end} od {count} zapisov.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Either "name" or "value" must be specified for CDataColumn.',
  'No results found.' => 'Noben zapis ni bil najden.',
  'Not set' => 'Ni nastavljen.',
  'Please specify the "attributes" property.' => 'Please specify the "attributes" property.',
  'Please specify the "data" property.' => 'Please specify the "data" property.',
  'Sort by: ' => 'Uredi po:',
  'The "dataProvider" property cannot be empty.' => 'The "dataProvider" property cannot be empty.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.',
  'The property "itemView" cannot be empty.' => 'The property "itemView" cannot be empty.',
  'Total {count} result(s).' => 'Skupaj zapisov: {count}',
  'Update' => 'Uredi',
  'View' => 'Pogled',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} must specify "model" and "attribute" or "name" property values.',
  'Are you sure you want to delete this item?' => 'Ali ste prepričani, da želite izbrisati ta element?'
);
