# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0050_auto_20160913_2121'),
        ('bober_si', '0003_auto_20151028_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default=b'', max_length=1024)),
                ('competitor_name', models.TextField(blank=True)),
                ('school_name', models.TextField(blank=True)),
                ('group_name', models.TextField(blank=True)),
                ('serial', models.CharField(blank=True, default=b'', max_length=64, unique=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bober_simple_competition.Attempt')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('group_name', models.CharField(max_length=256)),
                ('template', models.CharField(max_length=256)),
                ('threshold', models.FloatField()),
                ('serial_prefix', models.CharField(max_length=256)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bober_simple_competition.Competition')),
                ('questionset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bober_simple_competition.CompetitionQuestionSet')),
            ],
        ),
        migrations.CreateModel(
            name='AwardFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'/tmp')),
                ('recipients', models.ManyToManyField(blank=True, to='bober_simple_competition.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='schoolteachercode',
            name='competition_questionset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bober_simple_competition.CompetitionQuestionSet'),
        ),
        migrations.AddField(
            model_name='attemptaward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bober_si.Award'),
        ),
        migrations.AddField(
            model_name='attemptaward',
            name='files',
            field=models.ManyToManyField(to='bober_si.AwardFile'),
        ),
        migrations.AddField(
            model_name='attemptaward',
            name='revoked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bober_simple_competition.Profile'),
        ),
    ]
