# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models

def award_min_half_max(apps, schema_editor):
    Award = apps.get_model("bober_si", "Award")
    for award in Award.objects.all():
        if award.name == "bronasto":
            max_score = award.questionset.questionset.questions.all().aggregate(
                    models.Sum('max_score'))['max_score__sum']
            award.min_threshold = float(max_score)/2
        else:
            min_threshold = award.threshold
        award.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bober_si', '0005_school_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='min_threshold',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.RunPython(award_min_half_max, reverse_code=migrations.RunPython.noop),
    ]
