# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0053_profile_date_of_birth'),
        ('bober_si', '0006_award_min_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRecognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=256)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bober_simple_competition.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRecognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bober_simple_competition.Profile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bober_si.CompetitionRecognition')),
            ],
        ),
    ]
