# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_si', '0008_auto_20170112_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='from_place',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='to_place',
            field=models.IntegerField(null=True),
        ),
    ]
