# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_si', '0009_auto_20170113_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='from_place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='to_place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
