# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_si', '0010_auto_20170113_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='replaces',
            field=models.ManyToManyField(related_name='_award_replaces_+', to='bober_si.Award'),
        ),
    ]
