# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0054_auto_20170129_1434'),
        ('bober_si', '0012_auto_20170114_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionrecognition',
            name='serial_prefix',
            field=models.CharField(default='solsko', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherrecognition',
            name='note',
            field=models.CharField(blank=True, default=b'', max_length=1024),
        ),
        migrations.AddField(
            model_name='teacherrecognition',
            name='revoked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revoked_teacherrecognition_set', to='bober_simple_competition.Profile'),
        ),
    ]
