# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_si', '0013_auto_20170129_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='icon',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
