# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_si', '0014_award_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrecognition',
            name='recipient',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
