# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bober_si', '0015_teacherrecognition_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptaward',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='attemptaward',
            name='serial',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='replaces',
            field=models.ManyToManyField(blank=True, related_name='replaced_by', to='bober_si.Award'),
        ),
        migrations.AlterField(
            model_name='awardfile',
            name='file',
            field=models.FileField(upload_to='/tmp'),
        ),
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('ELEMENTARY', 'Elementary school'), ('HIGHSCHOOL', 'High school'), ('KINDERGARDEN', 'Kindergarden')], max_length=24),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolcategoryquestionsets',
            name='school_category',
            field=models.CharField(choices=[('ELEMENTARY', 'Elementary school'), ('HIGHSCHOOL', 'High school'), ('KINDERGARDEN', 'Kindergarden')], max_length=24),
        ),
        migrations.AlterField(
            model_name='teacherrecognition',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
