# Generated by Django 3.2.9 on 2021-11-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bober_simple_competition', '0061_auto_20211101_2231'),
        ('bober_si', '0017_auto_20180828_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrecognition',
            name='files',
            field=models.ManyToManyField(to='bober_si.AwardFile'),
        ),
        migrations.AlterField(
            model_name='attemptaward',
            name='files',
            field=models.ManyToManyField(blank=True, to='bober_si.AwardFile'),
        ),
        migrations.AlterField(
            model_name='attemptaward',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bober_simple_competition.profile'),
        ),
    ]
