# Generated by Django 6.0.3 on 2026-03-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bober_si", "0018_auto_20211101_2231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionrecognition",
            name="serial_prefix",
            field=models.CharField(max_length=32),
        ),
    ]
